export const ACTION_LIST: Array<string> = [
  'Give him/her a sensual message',
  'Send him/her a naked text tomorrow',
  'Make a movie for him/her',
  'Masturebate for you partner',
  'Shave your pubic hair',
  'Find pornography to watch together',
  'Use nipple clamps',
  'Submit to your partner for a spanking',
  'Be a submissive servant',
  'Have your partner wear your panties',
  'Tie your partners hands and legs then roll again for action',
  'Remove partners panties with your mouth',
  'Sit on top of partner and wet yourself while wearing panties. Minimum 10 seconds',
  'Dress partner as opposite sex. make them pleasure you as that role',
  'Lose this turn',
  'Dress your partner in your panties and make them do a photo shoot for you',
  'Perform oral on partner to point of orgasm but stop before release',
  'Partner must stand naked in bedroom window with hands on glass while spanked 15 times',
  'Tie partners hands behind back and rub ice cubes on nipples for 1 min',
  'Sit on his face forcefully',
  'She must lay on her back while he kneels over her head. He forces her to pleasure him orally',
  'She lays on her back. He straddles her and lightly slaps her breasts 5 times each',
  'She bends over the bed. He puts fingers where he wants for 30 seconds',
  'He is spreadeagle on his back. She can do whatever she wants for 2 minutes',
  'She is spreadeagle on her stomach. He can do whatever he wants for 2 minutes',
  'She is handcuffed behind her back. He gets to pinch her nipples for 30 seconds',
  'He is handcuffed behind his back. She sucks his balls for 30 seconds',
  'He performs cunnilingus while pinching her nipples for 30 seconds',
  'She gives a blowjob while playing with his balls for 30 seconds',
  '1 minute of sex. He chooses position',
  '1 minute of sex. She chooses position',
  'Kiss all over her naughty parts for 30 seconds',
  'Kiss all over his naughty parts for 30 seconds',
  'He is on his knees. She forces him to service her for 30 seconds',
  'She is on her knees. He forces her to service him for 30 seconds',
  'She bends over and he eats EVERYTHING for 1 minute',
  'She sits on his face. He tongues both holes for 45 seconds',
  'He gets on his back and she grinds her genitals on his mouth for 1 minute',
  '69 for 2 minute',
  'He puts 2 finger in her genital amd massage G spot for 1 minute',
  'She jerks him off for 45 seconds',
  'Pull her hair while doggy style for 1 minute',
  'Reverse cow girl for 1 minute',
  'Make him stand up, spread his legs, and squeeze each nut for 15 seconds',
  'Make her deepthroat your dick at least 5 times',
  'Jerk him off while sucking his balls',
  'Fuck him while slapping his face',
  'Recieve a massage',
  'Make him lick anywhere you want',
  'Jerk him off while sucking his balls',
  'Shave your pussy and let him eat your afterward to multiple orgasms',
  'Dress in/as anything he wants for a Fantasy night',
  'Shave her pussy and let him eat her afterward to multiple orgasms',
];
