export const TRUTH: Array<string> = [
    'Truth: When was the last time you masturbated? What was it to?',
    'Truth: Have you tried anal sex? Would you?',
    'Truth: Do you like to watch porn together? What type?',
    'Truth: Shaved, trimmed or unmanaged pubes?',
    'Truth: Girls what is the biggest cock you have seen/ guys what are the biggest tits you have seen that are not your partners',
    'Truth: Have you ever tasted cum?',
    'Truth: Have you ever had a threesome? Would you? Male or female?',
    'Truth: How many people have you been naked with besides your current partner?',
    'Truth: Have you done any of the following, just say yes or no for each: gangbang, anal sex, 69, toy play, sex outside',
    'Truth: Would you rather never have sex again OR let your partner have sex with someone else once',
    'Truth: Describe to your partner how you masturbate/cum',
    'Truth: Would you go to a nude beach with your partner?',
    'Truth: Would you be willing to share your partner? Describe the person you share with',
    'Truth: Have you watched porn with your partner? Have you watched porn with a previous partner or friend?',
    'Truth: Spit or swallow?',
    'Truth: Have you ever been to a strip club/ sex show. Explain!',
    'Truth: Would you rather have a threesome with someone of the same sex OR make a porn movie with your partner',
    'Truth: Describe something sexual/naked you have done with someone that is not your current partner',
    'Truth: What one sexual experience do you think about most often?',
    'Truth: What’s your biggest sexual fear?',
    'Truth: Would you prefer a big cock or sexy body?',
    'Truth: Do you wish your partner was kinkier/naughtier?',
    'Truth: Have you ever been fucked at a party?',
    'Truth: Tell partner a fantasy you would like to try',
    'Truth: Get partner to name 3 celebrities: you must pick 1 to fight, 1 to fuck and 1 to holiday with',
    'Truth: Would you ever have a foursome with your partner? Name a couple you both know who you would',
    'Truth (girl only): Would you ever get fucked by more than one guy at a time?',
    'Truth: When is the last time you had a sex dream? What was it about?',
    'Truth: Would you have sex with someone else in front of your partner?',
]

export const DARE: Array<string> = [
    'Dare: Loose 3 layers',
    'Dare: Flash cock/ tits to partner for 30 seconds ( no covering)',
    'Dare: Loose 2 layer of clothing',
    'Dare: Give oral to partner while they make a quick phone call (does not matter to who)',
    'Dare: Loose all clothing below the waist',
    'Dare: Masturbate in front of partner for 30 seconds',
    'Dare: Watch a same sex porn of 7 minutes or less while masturbating',
    'Dare: Loose 3 layers OR demonstrate giving a handjob for 30 seconds',
    'Dare: Flash your cock/pussy to partner for 10 seconds (no covering)',
    'Dare (girl only): Bend over and let partner pleasure you from behind for 1 minute',
    'Dare: Remove all clothing OR roll again',
    'Dare: You must wear your partner\'s underwear for 3 rounds',
    'Dare: Google image search "erotic sex gif" and masturbate together with partner while scrolling through 15 images',
    'Dare: Remove all clothing except boots/shoes ( if not wearing shoes put some on, partners choice)',
    'Dare (guy only): Google image search " pulling out big cock gif" and give partner oral while she looks at 20 images',
    'Dare: Masturbate under covers for 1 minute',
    'Dare (girl only): Google image search for a "hot girl sex gif" and let him fuck you doggy style for 10 images',
    'Dare: Shave pubes completely OR only you do next 3 rolls in a row',
    'Dare: Rub cock/tits over partner\'s body from head down',
    'Dare: Go online and order me a sex toy you think I’d like',
    'Dare: Stand in position of partners choice for 30 seconds',
    'Dare: Give partner oral sex for 1 minute in position of their choice',
    'Dare: Flip a coin - heads you must go down on partner for 1 minute/tails you must masturbate them and yourself at the same time for 1 minute',
    'Dare (guy only): Give her a striptease OR let her tie you up (arms and legs) and do ANYTHING for 1 minute',
    'Dare (girl only): Deepthroat cock or 30 seconds OR tit wank him for 30 seconds',
    'Dare: 69 together for 1 minute',
    'Dare: Show me a porn video you’d want us to act out together',
    'Dare: Loose 2 layers (partner\'s choice which 2)',
    'Dare: Kiss her pussy OR lick his balls',
    'Dare: Both masturbate in front of each other for 1 minute. No touching each other only looking!',
    'Dare: You must do one of the following for 30 seconds: perform oral in front of window, anal sex, streak outside, handstand sex',
    'Dare: Masturbate for 3 minutes while saying the name of someone other than your partner, fantasize about that person',
    'Dare: Massage partner for 3 minutes anywhere of their choice',
]